/**
 * Type Name Normalizer
 *
 * Maps alternative vulnerability type names to their canonical form.
 * This handles naming variations between different tools/scripts.
 */

/**
 * Mapping of alternative names to canonical detection type names
 * Key: Alternative name (from injection scripts, external tools, etc.)
 * Value: Canonical name (used in our detectors)
 */
export const TYPE_NAME_ALIASES: Record<string, string> = {
  // ==================== PASSWORD VARIATIONS ====================
  PASSWORDNEVEREXPIRES: 'PASSWORD_NEVER_EXPIRES',
  PASSWORD_NEVER_EXPIRES_FLAG: 'PASSWORD_NEVER_EXPIRES',
  PASSWORDNOTREQUIRED: 'PASSWORD_NOT_REQUIRED',
  PASSWORD_NOT_REQUIRED_FLAG: 'PASSWORD_NOT_REQUIRED',
  REVERSIBLEENCRYPTION: 'REVERSIBLE_ENCRYPTION',
  REVERSIBLE_ENCRYPTION_FLAG: 'REVERSIBLE_ENCRYPTION',
  PASSWORDINDESCRIPTION: 'PASSWORD_IN_DESCRIPTION',
  PASSWORD_IN_DESC: 'PASSWORD_IN_DESCRIPTION',
  EMPTY_PASSWORD: 'PASSWORD_NOT_REQUIRED',
  UNIXUSERPASSWORD_CLEAR: 'UNIX_USER_PASSWORD',
  PASSWORD_COMMON_PATTERNS: 'PASSWORD_DICT_ATTACK_RISK',

  // ==================== KERBEROS VARIATIONS ====================
  KERBEROASTABLE: 'KERBEROASTING_RISK',
  KERBEROASTABLE_WEAKPASSWORD: 'KERBEROASTING_RISK',
  KERBEROASTABLE_WEAK: 'KERBEROASTING_RISK',
  ASREPROASTABLE: 'ASREP_ROASTING_RISK',
  ASREP_ROASTABLE: 'ASREP_ROASTING_RISK',
  ADMIN_ASREP: 'ADMIN_ASREP_ROASTABLE',
  PRIVILEGED_ASREP: 'ADMIN_ASREP_ROASTABLE',
  ADMIN_ASREP_ROASTING: 'ADMIN_ASREP_ROASTABLE',
  DES_ENABLED: 'WEAK_ENCRYPTION_DES',
  DES_ENCRYPTION: 'WEAK_ENCRYPTION_DES',
  USE_DES_KEY_ONLY: 'WEAK_ENCRYPTION_DES',
  UNCONSTRAINEDDELEGATION: 'UNCONSTRAINED_DELEGATION',
  UNCONSTRAINED_DELEG: 'UNCONSTRAINED_DELEGATION',
  CONSTRAINEDDELEGATION: 'CONSTRAINED_DELEGATION',
  CONSTRAINED_DELEG: 'CONSTRAINED_DELEGATION',
  KERBEROS_TICKET_LIFETIME_LONG: 'KERBEROS_WEAK_CONFIG',

  // ==================== COMPUTER VARIATIONS ====================
  // Stale/Inactive computers
  COMPUTER_STALE_INACTIVE: 'COMPUTER_STALE_INACTIVE',
  COMPUTER_STALE: 'COMPUTER_STALE_INACTIVE',
  STALE_COMPUTER: 'COMPUTER_STALE_INACTIVE',

  // Password age
  COMPUTER_OLD_PASSWORD: 'COMPUTER_PASSWORD_OLD',
  COMPUTER_PASSWORD_NOT_CHANGED: 'COMPUTER_PASSWORD_OLD',

  // LAPS
  COMPUTER_NO_LAPS: 'COMPUTER_NO_LAPS',
  NO_LAPS: 'COMPUTER_NO_LAPS',
  LAPS_NOT_DEPLOYED: 'COMPUTER_NO_LAPS',

  // Pre-created (disabled + never logged on) - different from never logged on (enabled)
  COMPUTER_PRECREATED: 'COMPUTER_PRE_CREATED',
  COMPUTER_STAGED: 'COMPUTER_PRE_CREATED',

  // Legacy protocols
  COMPUTER_LEGACY_PROTOCOL_SMBV1: 'COMPUTER_LEGACY_PROTOCOL',
  COMPUTER_SMBV1: 'COMPUTER_LEGACY_PROTOCOL',
  SMB1_ENABLED: 'COMPUTER_LEGACY_PROTOCOL',
  SMBV1_ENABLED: 'COMPUTER_LEGACY_PROTOCOL',

  // SMB Signing
  COMPUTER_SMB_SIGNING_DISABLED: 'COMPUTER_SMB_SIGNING_DISABLED',
  SMB_SIGNING_DISABLED: 'COMPUTER_SMB_SIGNING_DISABLED',
  SMB_SIGNING_NOT_REQUIRED: 'COMPUTER_SMB_SIGNING_DISABLED',

  // Disabled not deleted
  COMPUTER_DISABLED_NOT_DELETED: 'COMPUTER_DISABLED_NOT_DELETED',
  DISABLED_COMPUTER_NOT_DELETED: 'COMPUTER_DISABLED_NOT_DELETED',

  // Pre-Windows 2000
  COMPUTER_PRE_WIN2000: 'COMPUTER_PRE_WINDOWS_2000',
  COMPUTER_PRE_2000: 'COMPUTER_PRE_WINDOWS_2000',
  PRE_WINDOWS_2000_COMPUTER: 'COMPUTER_PRE_WINDOWS_2000',

  // Description sensitive
  COMPUTER_SENSITIVE_DESCRIPTION: 'COMPUTER_DESCRIPTION_SENSITIVE',
  COMPUTER_DESC_SENSITIVE: 'COMPUTER_DESCRIPTION_SENSITIVE',

  // RBCD
  COMPUTER_RBCD: 'COMPUTER_RBCD',
  RBCD: 'COMPUTER_RBCD',
  RESOURCE_BASED_CONSTRAINED_DELEGATION: 'COMPUTER_RBCD',

  // Duplicate SPN
  COMPUTER_DUPLICATE_SPN: 'COMPUTER_DUPLICATE_SPN',
  DUPLICATE_SPN: 'COMPUTER_DUPLICATE_SPN',

  // ==================== ACCOUNT VARIATIONS ====================
  SIDHISTORY: 'SID_HISTORY',
  SID_HISTORY_PRESENT: 'SID_HISTORY',
  NOTINPROTECTEDUSERS: 'NOT_IN_PROTECTED_USERS',
  NOT_PROTECTED_USERS: 'NOT_IN_PROTECTED_USERS',
  ADMINCOUNT_ORPHANED: 'ADMIN_COUNT_ORPHANED',
  ORPHANED_ADMINCOUNT: 'ADMIN_COUNT_ORPHANED',
  DISABLEDACCOUNTINPRIVGROUP: 'DISABLED_ACCOUNT_IN_ADMIN_GROUP',
  DISABLED_ADMIN: 'DISABLED_ACCOUNT_IN_ADMIN_GROUP',
  STALEACCOUNT: 'STALE_ACCOUNT',
  STALE_USER: 'STALE_ACCOUNT',
  INACTIVE_180: 'STALE_ACCOUNT',
  INACTIVE_ACCOUNT: 'INACTIVE_365_DAYS',
  INACTIVE_USER: 'INACTIVE_365_DAYS',
  TEST_ACCOUNT: 'TEST_ACCOUNT',
  TESTACCOUNT: 'TEST_ACCOUNT',
  SHARED_ACCOUNT: 'SHARED_ACCOUNT',
  SHAREDACCOUNT: 'SHARED_ACCOUNT',
  SMARTCARD_NOT_REQUIRED: 'SMARTCARD_NOT_REQUIRED',
  NO_SMARTCARD: 'SMARTCARD_NOT_REQUIRED',
  SHADOW_CREDENTIALS: 'SHADOW_CREDENTIALS',
  MSDS_KEYCREDENTIALLINK: 'SHADOW_CREDENTIALS',
  FOREIGN_SECURITY_PRINCIPALS: 'FOREIGN_SECURITY_PRINCIPAL',

  // ==================== SERVICE ACCOUNT VARIATIONS ====================
  SERVICE_ACCOUNT_NAMING: 'SERVICE_ACCOUNT_NAMING',
  SVC_ACCOUNT: 'SERVICE_ACCOUNT_NAMING',
  SERVICE_ACCOUNT_OLD_PASSWORD: 'SERVICE_ACCOUNT_OLD_PASSWORD',
  SVC_OLD_PASSWORD: 'SERVICE_ACCOUNT_OLD_PASSWORD',
  SERVICE_ACCOUNT_PRIVILEGED: 'SERVICE_ACCOUNT_PRIVILEGED',
  SVC_PRIVILEGED: 'SERVICE_ACCOUNT_PRIVILEGED',
  SERVICE_ACCOUNT_NO_PREAUTH: 'SERVICE_ACCOUNT_NO_PREAUTH',
  SVC_NO_PREAUTH: 'SERVICE_ACCOUNT_NO_PREAUTH',
  SERVICE_ACCOUNT_INTERACTIVE: 'SERVICE_ACCOUNT_INTERACTIVE',
  SVC_INTERACTIVE: 'SERVICE_ACCOUNT_INTERACTIVE',

  // ==================== ACL VARIATIONS ====================
  ACL_GENERICALL_DA: 'ACL_GENERICALL',
  ACL_GENERICALL_DOMAIN_ADMINS: 'ACL_GENERICALL',
  ACL_GENERICWRITE_SENSITIVEGROUP: 'ACL_GENERICWRITE',
  ACL_GENERICWRITE_USER: 'ACL_GENERICWRITE',
  ACL_WRITEDACL_OU: 'ACL_WRITEDACL',
  ACL_WRITEDACL_SENSITIVEGROUP: 'ACL_WRITEDACL',
  ACL_WRITEOWNER_SENSITIVEGROUP: 'ACL_WRITEOWNER',
  ACL_ADDMEMBER: 'ACL_ADD_MEMBER',
  ACL_ADD_MEMBER_GROUP: 'ACL_ADD_MEMBER',
  ACL_DCSYNC: 'ACL_DS_REPLICATION_GET_CHANGES',
  DCSYNC: 'ACL_DS_REPLICATION_GET_CHANGES',
  DCSYNC_RIGHTS: 'ACL_DS_REPLICATION_GET_CHANGES',
  ORPHANED_ACES: 'ORPHANED_ACL_ENTRIES',
  NESTEDGROUPPATH: 'DANGEROUS_GROUP_NESTING',
  NESTED_GROUP_PATH: 'DANGEROUS_GROUP_NESTING',

  // ==================== ADCS VARIATIONS ====================
  ESC1_VULNERABLE_CERTIFICATE_TEMPLATE: 'ESC1_VULNERABLE_TEMPLATE',
  ESC1: 'ESC1_VULNERABLE_TEMPLATE',
  ESC2_ANY_PURPOSE_EKU: 'ESC2_ANY_PURPOSE',
  ESC2: 'ESC2_ANY_PURPOSE',
  ESC3: 'ESC3_ENROLLMENT_AGENT',
  ESC4: 'ESC4_VULNERABLE_TEMPLATE_ACL',
  ESC5: 'ESC5_PKI_OBJECT_ACL',
  ESC6_EDITF_ATTRIBUTESUBJECTALTNAME2: 'ESC6_EDITF_FLAG',
  ESC6: 'ESC6_EDITF_FLAG',
  ESC7: 'ESC7_CA_VULNERABLE_ACL',
  ESC8: 'ESC8_HTTP_ENROLLMENT',
  ESC9: 'ESC9_NO_SECURITY_EXTENSION',
  ESC10: 'ESC10_WEAK_CERTIFICATE_MAPPING',
  ESC11: 'ESC11_ICERT_REQUEST_ENFORCEMENT',

  // ==================== GPO VARIATIONS ====================
  GPO_LINKPOISONING: 'GPO_LINK_POISONING',
  GPO_LINK_POISON: 'GPO_LINK_POISONING',
  GPO_AUTHENTICATED_USERS_APPLY: 'GPO_WEAK_PERMISSIONS',
  GPO_NO_SECURITY_FILTERING: 'GPO_WEAK_PERMISSIONS',
  GPO_PASSWORD_IN_SYSVOL: 'GPO_PASSWORD_IN_SYSVOL',
  GPO_SYSVOL_PASSWORD: 'GPO_PASSWORD_IN_SYSVOL',
  CPASSWORD: 'GPO_PASSWORD_IN_SYSVOL',
  GPO_CREATOR_OWNERS_MEMBER: 'GPO_MODIFY_RIGHTS',
  GPO_DANGEROUS_PERMISSIONS: 'GPO_MODIFY_RIGHTS',
  // Note: GPO_LAPS_NOT_DEPLOYED is distinct from COMPUTER_NO_LAPS
  // - GPO_LAPS_NOT_DEPLOYED: No GPO found deploying LAPS
  // - COMPUTER_NO_LAPS: Individual computers without LAPS attributes

  // ==================== EXCESSIVE PRIVILEGES ====================
  EXCESSIVEPRIVILEGES_DA: 'NOT_IN_PROTECTED_USERS',
  EXCESSIVE_PRIVILEGES_DA: 'NOT_IN_PROTECTED_USERS',
  EXCESSIVEPRIVILEGES_ENTERPRISEADMIN: 'NOT_IN_PROTECTED_USERS',
  EXCESSIVE_PRIVILEGES_EA: 'NOT_IN_PROTECTED_USERS',
  EXCESSIVEPRIVILEGES_AO: 'ACCOUNT_OPERATORS_MEMBER',
  EXCESSIVE_PRIVILEGES_AO: 'ACCOUNT_OPERATORS_MEMBER',
  EXCESSIVEPRIVILEGES_BO: 'BACKUP_OPERATORS_MEMBER',
  EXCESSIVE_PRIVILEGES_BO: 'BACKUP_OPERATORS_MEMBER',
  EXCESSIVEPRIVILEGES_PRINTOPS: 'PRINT_OPERATORS_MEMBER',
  EXCESSIVE_PRIVILEGES_PRINTOPS: 'PRINT_OPERATORS_MEMBER',
  EXCESSIVEPRIVILEGES_DNS: 'DNS_ADMINS_MEMBER',
  EXCESSIVE_PRIVILEGES_DNS: 'DNS_ADMINS_MEMBER',
  EXCESSIVEPRIVILEGES_SCHEMAADMIN: 'NOT_IN_PROTECTED_USERS',
  EXCESSIVE_PRIVILEGES_SCHEMA: 'NOT_IN_PROTECTED_USERS',
  EXCESSIVEPRIVILEGES_RDP: 'DANGEROUS_BUILTIN_MEMBERSHIP',
  EXCESSIVE_PRIVILEGES_RDP: 'DANGEROUS_BUILTIN_MEMBERSHIP',

  // ==================== ATTACK PATHS ====================
  PATH_GPO_TO_DA: 'PATH_GPO_TO_DA',
  PATH_SERVICE_TO_DA: 'PATH_SERVICE_TO_DA',
  PATH_ASREP_TO_ADMIN: 'PATH_ASREP_TO_ADMIN',
  PATH_NESTED_ADMIN: 'PATH_NESTED_ADMIN',
  PATH_DELEGATION_CHAIN: 'PATH_DELEGATION_CHAIN',
  PATH_CERTIFICATE_ESC: 'PATH_CERTIFICATE_ESC',
  PATH_TRUST_LATERAL: 'PATH_TRUST_LATERAL',
  PATH_KERBEROASTING_TO_DA: 'PATH_KERBEROASTING_TO_DA',
  PATH_COMPUTER_TAKEOVER: 'PATH_COMPUTER_TAKEOVER',

  // ==================== GROUP VARIATIONS ====================
  OVERSIZED_GROUP_CRITICAL: 'OVERSIZED_GROUP_HIGH',
  OVERSIZED_GROUP: 'GROUP_EXCESSIVE_MEMBERS',
  AUTHENTICATED_USERS_IN_ACLS: 'EVERYONE_IN_ACL',
  EVERYONE_IN_ACLS: 'EVERYONE_IN_ACL',
  EXCESSIVE_ADMINS: 'EXCESSIVE_PRIVILEGED_ACCOUNTS',
  TOO_MANY_ADMINS: 'EXCESSIVE_PRIVILEGED_ACCOUNTS',
  EXCESSIVE_DOMAIN_ADMINS: 'EXCESSIVE_PRIVILEGED_ACCOUNTS',

  // ==================== ADVANCED/CONFIG VARIATIONS ====================
  ADMIN_SD_HOLDER_MODIFIED: 'ADMINSDHOLDER_BACKDOOR',
  ADMINSD_HOLDER_MODIFIED: 'ADMINSDHOLDER_BACKDOOR',
  LAPS_PASSWORDREAD: 'LAPS_PASSWORD_READABLE',
  LAPS_READ: 'LAPS_PASSWORD_READABLE',
  LAPS_PASSWORD_LEAKED: 'LAPS_PASSWORD_LEAKED',
  SMB_V1_ENABLED: 'COMPUTER_LEGACY_PROTOCOL',
  ANONYMOUS_LDAP_ACCESS: 'ANONYMOUS_LDAP_ACCESS',
  ANONYMOUS_BIND: 'ANONYMOUS_LDAP_ACCESS',
  AUDIT_POLICY_WEAK: 'AUDIT_POLICY_WEAK',
  AUDIT_NOT_CONFIGURED: 'AUDIT_POLICY_WEAK',
  LDAP_CHANNEL_BINDING_DISABLED: 'LDAP_CHANNEL_BINDING_DISABLED',
  LDAP_SIGNING_DISABLED: 'LDAP_SIGNING_NOT_REQUIRED',
  POWERSHELL_LOGGING_DISABLED: 'POWERSHELL_LOGGING_DISABLED',
  PS_LOGGING_DISABLED: 'POWERSHELL_LOGGING_DISABLED',
  DANGEROUS_LOGON_SCRIPT: 'DANGEROUS_LOGON_SCRIPT',
  LOGON_SCRIPT_VULNERABLE: 'DANGEROUS_LOGON_SCRIPT',
  SERVER_NO_ADMIN_GROUP: 'SERVER_NO_ADMIN_GROUP',
  RECYCLE_BIN_DISABLED: 'RECYCLE_BIN_DISABLED',
  AD_RECYCLE_BIN_DISABLED: 'RECYCLE_BIN_DISABLED',

  // ==================== USER ACCOUNT VARIATIONS ====================
  USER_CANNOT_CHANGE_PASSWORD: 'USER_CANNOT_CHANGE_PASSWORD',
  CANNOT_CHANGE_PASSWORD: 'USER_CANNOT_CHANGE_PASSWORD',
  SEENABLEDELEGATIONPRIVILEGE: 'DELEGATION_PRIVILEGE',
  SE_ENABLE_DELEGATION: 'DELEGATION_PRIVILEGE',
  SUSPICIOUSACCOUNTNAME: 'TEST_ACCOUNT',
  SUSPICIOUS_ACCOUNT: 'TEST_ACCOUNT',
  SUSPICIOUSSIDPROPERTIES: 'PRIMARYGROUPID_SPOOFING',
  PRIMARYGROUPID_MODIFIED: 'PRIMARYGROUPID_SPOOFING',

  // ==================== COMPUTER ACL ====================
  COMPUTER_ACL_GENERICALL: 'COMPUTER_ACL_ABUSE',
  COMPUTER_LOCAL_ADMIN_MAPPING: 'COMPUTER_IN_ADMIN_GROUP',
  LOCAL_ADMIN_MAPPING: 'COMPUTER_IN_ADMIN_GROUP',

  // ==================== LAPS VARIATIONS ====================
  COMPUTER_WEAK_LAPS: 'LAPS_LEGACY_ATTRIBUTE',
  WEAK_LAPS: 'LAPS_LEGACY_ATTRIBUTE',

  // ==================== TRUST VARIATIONS ====================
  TRUST_LATERAL: 'PATH_TRUST_LATERAL',
  FOREST_TRUST_VULNERABLE: 'TRUST_MISCONFIGURED',
  EXTERNAL_TRUST: 'TRUST_EXTERNAL',

  // ==================== ULTRA VULNERABLE (TEST) ====================
  ULTRA_VULNERABLE_USER: 'CRITICAL_VULNERABLE_USER',
};

/**
 * Normalize a vulnerability type name to its canonical form
 * @param typeName The type name to normalize
 * @returns The canonical type name
 */
export function normalizeTypeName(typeName: string): string {
  // First, uppercase and remove extra whitespace
  const normalized = typeName.toUpperCase().trim();

  // Check if there's an alias
  if (TYPE_NAME_ALIASES[normalized]) {
    return TYPE_NAME_ALIASES[normalized];
  }

  // Return as-is if no alias found
  return normalized;
}

/**
 * Check if two type names are equivalent (same canonical form)
 * @param type1 First type name
 * @param type2 Second type name
 * @returns true if they map to the same canonical type
 */
export function areTypesEquivalent(type1: string, type2: string): boolean {
  return normalizeTypeName(type1) === normalizeTypeName(type2);
}

/**
 * Get all known type names (canonical + aliases)
 */
export function getAllKnownTypes(): string[] {
  const aliases = Object.keys(TYPE_NAME_ALIASES);
  const canonical = Object.values(TYPE_NAME_ALIASES);
  return [...new Set([...aliases, ...canonical])];
}
